#!/bin/sh

LC_TIME="en_US"
export LC_TIME

die () {
   echo "*** mkconfig.sh: $*" 1>&2
   exit 1
}

[ -f makefile ] || die "can not find 'makefile'"

cat<<EOF
/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
EOF

echo "#define LGL_OS \"`uname -srmn`\""
echo "#define LGL_COMPILED \"`date`\""
cat<<EOF
#define LGL_RELEASED "Sun Nov 29 18:40:12 CET 2015"
#define LGL_VERSION "bal"
#define LGL_ID "2293bef0a4bd680210f6f5a453efa8b0a26f53ee"
EOF
