/**********************************************************/
/* Automatically generated by './mkconfig': do note edit! */
/**********************************************************/
#define BTOR_CC "gcc (GCC) 5.2.0"
#define BTOR_CXX "g++"
#define BTOR_CFLAGS "-W -Wall -Wextra -Wredundant-decls -fPIC -O3 -DNDEBUG -DNBTORLOG -DBTOR_USE_LINGELING -DBTOR_ENABLE_BETA_REDUCTION_PROBING"
#define BTOR_OS "Linux pino 4.2.4-1-ARCH x86_64"
#define BTOR_COMPILED "Sun Nov 29 18:31:55 CET 2015"
#define BTOR_RELEASED "Sun Nov 29 18:31:55 CET 2015"
#define BTOR_VERSION "2.2.0"
#define BTOR_ID "8209e6ee93bc06a81d7bcf87e6e7117a04382970"
